# Generated by Django 5.1.1 on 2024-10-08 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postal.parcel')),
            ],
        ),
    ]
