# Generated by Django 5.1.1 on 2024-10-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0005_parceltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceltype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parceltype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
