# Generated by Django 5.1.1 on 2024-10-11 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0006_parceltype_description_alter_parceltype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='parcel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='postal.parceltype'),
        ),
    ]
