# Generated by Django 5.1.1 on 2024-10-11 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0007_parcel_parcel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='sender',
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_name',
            field=models.CharField(default='Unknown Sender', max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
