# Generated by Django 5.1.1 on 2024-10-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0009_paymenttype_parcel_description_parcel_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('office', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['office'],
            },
        ),
    ]
