# Generated by Django 5.1.1 on 2024-10-16 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0010_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_parcels', to='postal.station'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='origin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_parcels', to='postal.station'),
        ),
    ]
