# Generated by Django 5.1.1 on 2024-10-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0011_alter_parcel_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_to_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver_pobox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_pobox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='receiver_phone',
            field=models.CharField(default='254', max_length=15),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sender_phone',
            field=models.CharField(default='254', max_length=15),
        ),
    ]
