# Generated by Django 5.1.1 on 2024-10-18 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0013_driver_vehicle_parcel_driver_parcel_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('schedule_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_schedules', to='postal.station')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postal.driver')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_schedules', to='postal.station')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='postal.vehicle')),
            ],
            options={
                'unique_together': {('origin_station', 'destination_station', 'schedule_date')},
            },
        ),
    ]
