# Generated by Django 5.1.1 on 2024-10-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0014_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
