# Generated by Django 5.1.1 on 2024-10-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0015_parcel_is_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
