# Generated by Django 5.1.1 on 2024-10-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0016_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='postal.station'),
        ),
    ]
