# Generated by Django 5.1.1 on 2024-10-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0017_driver_current_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='receiver_pobox',
            new_name='receiver_POBOX',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='sender_pobox',
            new_name='sender_POBOX',
        ),
    ]
