# Generated by Django 5.1.1 on 2024-10-20 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0018_rename_receiver_pobox_parcel_receiver_pobox_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='parcelevent',
            name='note',
        ),
        migrations.AddField(
            model_name='parcelevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcelevent',
            name='event_type',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Ready for dispatch', 'Ready for dispatch'), ('Dispatched', 'Dispatched'), ('In transit', 'In transit'), ('Delivered', 'Delivered'), ('Received', 'Received'), ('Under incidence', 'Under incidence')], max_length=50),
        ),
    ]
