# Generated by Django 5.1.1 on 2024-11-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal', '0020_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
